version: "3"

services:
  retro-db:
    image: mariadb:10.7
    restart: unless-stopped
    container_name: retro-db
    volumes:
      - retro-db:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_ROOT_PASSWORD: retro
      MYSQL_DATABASE: retro
    ports:
      - "3306:3306"
    networks:
      - retro-back-local
  retro-service:
    build:
      context: ../
    restart: unless-stopped
    container_name: retro-service
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - JWT_SECRET
      - DATABASE_URL=mysql://root:retro@retro-db:3306/retro?characterEncoding=utf8&useUnicode=true
      - CALLBACK_URL
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - retro-back-local
      - reverse-proxy_global
    depends_on:
      - retro-db

networks:
  retro-back-local:
  reverse-proxy_global:
    external: true

volumes:
  retro-db:
